name: Mirror and run GitLab CI

on: [push, pull_request]

jobs:
  gitlab_server_mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror and trigger CI job at https://gitlab.com
      uses: stenongithub/gitlab-mirror-and-ci-action@0.2.8
      with:
        args: "https://gitlab.com/pghysels/STRUMPACK.git"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "pghysels"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "30660136"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POLL_TIMEOUT: "800"
